import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import {
  buildClientSchema,
  getIntrospectionQuery,
  printSchema,
  type IntrospectionQuery,
} from 'graphql';

const SCHEMA_ENDPOINT = process.env.AMBOSS_SCHEMA_URL ?? 'https://rails.amboss.tech/graphql';
const OUTPUT_PATH = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'schema',
  'rails.graphql',
);

async function main(): Promise<void> {
  const response = await fetch(SCHEMA_ENDPOINT, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ query: getIntrospectionQuery() }),
  });

  if (!response.ok) {
    throw new Error(`Introspection failed: ${response.status} ${response.statusText}`);
  }

  const json = (await response.json()) as { data?: IntrospectionQuery; errors?: unknown };
  if (json.errors || !json.data) {
    throw new Error(`Introspection errors: ${JSON.stringify(json.errors)}`);
  }

  const schema = buildClientSchema(json.data);
  const sdl = printSchema(schema);
  await writeFile(
    OUTPUT_PATH,
    `# Generated by refresh-schema from ${SCHEMA_ENDPOINT}\n# Do not edit by hand.\n\n${sdl}\n`,
    'utf8',
  );
  console.warn(`Wrote ${OUTPUT_PATH}`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
